### ISSUE TITLE
Ошибка в регулярном выражении

### ISSUE THREAD

**Issue by pandvik** [shishkovIS/K#2]
Expression_Manager::check_expression() при создании регулярки. Ветка master

вылетает на входе:
1 1
=A1

**Comment by shishkovIS** [comment]
Разбираюсь с этим, но пока не понятно

**Comment by shishkovIS** [comment]
Проблема решена, заливаю в основную ветку. Фишка в том, что экранирование символов в regex осуществляется с помощью \\character.
